import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import MonitoringStatus, { observedTime } from '@/Components/MonitoringStatus';
import { Head, Link, router } from '@inertiajs/react';
import axios from 'axios';
import { useState } from 'react';

type Incident = { id: number; state: string; severity: string; reason_code: string; version: number; flapping: boolean; first_failed_at: string; confirmed_down_at: string; first_recovery_sample_at: string | null; confirmed_recovered_at: string | null; closure_summary: string | null; environment_kind: string; impacted_projects: { id: number; name: string }[]; observations: { id: number; scheduled_at: string; outcome: string; source_type: string; reason_code: string; evidence: Record<string, unknown>; fake: boolean; maintenance: boolean }[]; timeline: { id: number; event: string; occurred_at: string; suppressed: boolean }[]; workflow_boundary: string };
export default function IncidentPage({ organization, incident, canManage, assignees }: { organization: { id: number; timezone: string }; incident: Incident; canManage: boolean; assignees: { id: number; name: string }[] }) {
    const [summary, setSummary] = useState(''); const [assignee, setAssignee] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
    async function action(name: string) {
        setBusy(true); setError('');
        try { await axios.post(`/api/v1/organizations/${organization.id}/monitoring/incidents/${incident.id}/${name}`, { version: incident.version, summary, assignee_user_id: assignee ? Number(assignee) : null }, { headers: { 'Idempotency-Key': crypto.randomUUID() } }); router.reload(); }
        catch (failure) { const status = axios.isAxiosError(failure) ? failure.response?.status : 0; setError(status === 409 ? 'Incident berubah. Muat ulang halaman sebelum mencoba lagi.' : 'Tindakan gagal. Periksa izin, assignee, recovery, dan ringkasan lalu coba kembali.'); }
        finally { setBusy(false); }
    }
    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold">Incident #{incident.id}</h2>}><Head title={`Incident ${incident.id}`} /><main className="mx-auto max-w-5xl space-y-6 px-4 py-8">
        <Link className="underline" href={route('monitoring.overview', organization.id)}>← Overview</Link><section className="border bg-white p-5"><h3 className="text-lg font-semibold">{incident.reason_code} · {incident.severity}</h3><p className="mt-2">{incident.state} · {incident.environment_kind} {incident.flapping && '· ⚠ Stabilitas flapping'}</p><p className="mt-2">Proyek terdampak dalam scope: {incident.impacted_projects.map(project => project.name).join(', ')}</p><dl className="mt-4 grid gap-2 text-sm"><div>Gagal pertama: {observedTime(incident.first_failed_at, organization.timezone)}</div><div>Down terkonfirmasi: {observedTime(incident.confirmed_down_at, organization.timezone)}</div><div>Recovery pertama: {observedTime(incident.first_recovery_sample_at, organization.timezone)}</div><div>Recovery terkonfirmasi: {observedTime(incident.confirmed_recovered_at, organization.timezone)}</div></dl><p className="mt-3 text-xs text-slate-500">Downtime adalah estimasi dari interval probe pada satu lokasi.</p>{incident.closure_summary && <p className="mt-4">Ringkasan closure: {incident.closure_summary}</p>}</section>
        {canManage ? <section className="space-y-4 border bg-white p-5"><h3 className="font-semibold">Tindak lanjut operator</h3><div className="flex flex-wrap gap-3">{['acknowledge', 'investigate'].map(name => <button disabled={busy || ['resolved', 'closed'].includes(incident.state)} className="rounded border px-3 py-2 disabled:opacity-50" onClick={() => action(name)} key={name}>{name === 'acknowledge' ? 'Acknowledge' : 'Mulai investigasi'}</button>)}</div><label className="block">Assignee<select className="ml-3" value={assignee} onChange={event => setAssignee(event.target.value)}><option value="">Pilih operator</option>{assignees.map(user => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label><button disabled={busy || !assignee} className="rounded border px-3 py-2 disabled:opacity-50" onClick={() => action('assign')}>Assign</button><label className="block">Ringkasan tindakan/cause (cause boleh belum diketahui)<textarea className="mt-2 block w-full" value={summary} maxLength={2000} onChange={event => setSummary(event.target.value)} /></label><button disabled={busy || incident.state !== 'resolved' || !summary.trim()} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50" onClick={() => action('close')}>Tutup setelah recovery</button>{error && <p role="alert" className="text-red-700">{error}</p>}</section> : <p className="border-l-4 border-amber-400 bg-amber-50 p-4">Anda dapat membaca evidence; tindakan membutuhkan permission operator dan akses seluruh proyek terdampak.</p>}
        <section><h3 className="font-semibold">Timeline</h3><ol className="mt-3 space-y-2">{incident.timeline.map(event => <li key={event.id} className="border-l-2 border-slate-300 pl-4 text-sm">{observedTime(event.occurred_at.endsWith('Z') ? event.occurred_at : event.occurred_at.replace(' ', 'T') + 'Z', organization.timezone)} · {event.event} {event.suppressed && '· Alert disuppress saat maintenance'}</li>)}</ol></section>
        <section><h3 className="font-semibold">Evidence terakhir (maksimal 100)</h3><ul className="mt-3 space-y-3">{incident.observations.map(observation => <li className="border bg-white p-4" key={observation.id}><MonitoringStatus value={observation.outcome} /><span className="ml-3 text-sm">{observation.reason_code} · {observation.source_type} {observation.fake && '· Fixture'} {observation.maintenance && '· Maintenance'}</span><p className="mt-2 text-sm">{observedTime(observation.scheduled_at, organization.timezone)}</p><pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(observation.evidence, null, 2)}</pre></li>)}</ul></section><p className="text-sm text-slate-500">{incident.workflow_boundary}</p>
    </main></AuthenticatedLayout>;
}
