import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import axios from 'axios';
import { useState } from 'react';
type Delivery = { id: number; outbox_event_id: number; notification_kind: string; state: string; severity: string; attempts: number; result_code: string | null; available_at: string; sent_at: string | null; message_id: string | null; fake: boolean; duplicate_possible: boolean; revision: number };
type Finding = { id: number; version: number; code: string; state: string; action: string };
export default function Deliveries({ organization, health, canConfigure, counts, deliveries, findings }: { organization: { id: number; name: string }; health: { state: string; boundary: string }; canConfigure: boolean; counts: Record<string, number>; deliveries: Delivery[]; findings: Finding[] }) {
    const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
    return <AuthenticatedLayout header={<h1 className="text-xl font-semibold">Notification delivery · {organization.name}</h1>}><Head title="Notification delivery" /><div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><p>Integrasi: {health.state}. Sent berarti API menerima pesan dan message ID tercatat; bukan read receipt. Fake tidak membuktikan delivery live.</p><p>Ringkasan maksimal 1000 record terbaru dalam scope; daftar menampilkan maksimal 100. {Object.entries(counts).map(([s, n]) => `${s}: ${n}`).join(' · ')}</p><nav className="flex flex-wrap gap-4"><Link href={route('telegram.binding', organization.id)} className="underline">Binding pribadi</Link>{canConfigure && <><Link href={route('telegram.settings', organization.id)} className="underline">Konfigurasi Owner</Link><Link href={route('password.confirm')} className="underline">Konfirmasikan password sebelum acknowledge</Link></>}</nav>
        {message && <p role="status">{message}</p>}
        {findings.length > 0 && <section className="space-y-3"><h2 className="font-semibold">Action items Owner</h2>{findings.map(f => <article className="rounded border border-amber-200 bg-white p-4" key={f.id}><h3 className="font-semibold">{f.code} · {f.state}</h3><p>{f.action}</p>{f.state === 'open' && <button disabled={busy} className="mt-2 underline" onClick={async () => { setBusy(true); try { await axios.post(`/api/v1/organizations/${organization.id}/notifications/findings/${f.id}/acknowledge`, { version: f.version }); setMessage('Finding acknowledged; perbaikan/test tetap diperlukan.'); router.reload(); } catch { setMessage('Periksa akses, konfirmasi password dan versi terbaru.'); } finally { setBusy(false); } }}>Acknowledge finding</button>}</article>)}</section>}
        <ul className="divide-y rounded bg-white shadow">{deliveries.map(d => <li key={d.id} className="flex flex-wrap justify-between gap-3 p-4"><div><p className="font-semibold">Delivery #{d.id} · outbox #{d.outbox_event_id} · {d.notification_kind} · revision {d.revision}</p><p>{d.severity} · {d.state} · attempts {d.attempts} · {d.result_code ?? 'menunggu'}</p>{d.fake && <p>FAKE TESTING</p>}{d.duplicate_possible && <p className="text-amber-800">Pengiriman sebelumnya uncertain; duplicate mungkin terjadi.</p>}</div><div className="break-all text-sm"><p>Available {new Date(d.available_at).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })} WIB</p><p>{d.sent_at ? `Accepted ${new Date(d.sent_at).toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })} WIB · message ${d.message_id}` : 'Belum ada confirmed API acceptance'}</p></div></li>)}</ul>{deliveries.length === 0 && <p>Belum ada delivery dalam scope Anda. Event pending atau konfigurasi belum tersedia tidak berarti sent.</p>}
    </div></AuthenticatedLayout>;
}
